//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sdclient.rc
//
#define IDD_SYNCAGENT_DIALOG            102
#define IDD_CLIENT_DLG                  103
#define IDS_CONNTCTING                  105
#define IDS_CONNTCTED                   106
#define IDS_PAUSED                      107
#define IDS_START                       108
#define IDS_BALLOONTIP                  109
#define IDR_MAINFRAME                   128
#define IDD_PROXIES_PAGE_DLG            129
#define IDD_ACCOUNT_PAGE_DLG            130
#define IDB_FACCOUNT                    130
#define IDD_BANDWIDTH_PAGE_DLG          131
#define IDD_GENERAL_PAGE_DLG            132
#define IDB_FBANDWIDTH                  132
#define IDD_ABOUT_PAGE_DLG              133
#define IDB_FGENERAL                    133
#define IDB_FPROXIES                    135
#define IDR_TRAYICON_MENU               136
#define IDD_OPTIONS_DLG                 137
#define IDB_NACCOUNT                    137
#define IDB_NBANDWIDTH                  138
#define IDB_NGENERAL                    139
#define IDB_NPROXIES                    140
#define IDB_FABOUT                      141
#define IDB_NABOUT                      142
#define IDI_SYNCOK                      143
#define IDI_FIRST_SYNCING               144
#define IDI_NORMAL                      145
#define IDI_PAUSED                      147
#define IDB_PAUSED                      148
#define IDB_RUNING                      149
#define IDB_CONNECT                     150
#define IDB_BACKGROUND                  151
#define IDD_BUTTON_DLG                  153
#define IDD_ADD_PASSWD_DLG              154
#define IDD_CHG_PASSWD_DLG              155
#define IDD_SECURITY_PAGE_DLG           156
#define IDB_FSECURITY                   157
#define IDB_NSECURITY                   158
#define IDD_VALIDATE_DLG                159
#define IDD_MOVE_USERSPACE_DLG          160
#define IDD_ADVANCED_PAGE_DLG           161
#define IDB_NADVANCED                   162
#define IDB_BITMAP2                     163
#define IDB_FADVANCED                   163
#define IDD_SELECTIVE_DLG               164
#define IDD_DOWND_DIRES_DLG				165
#define IDB_FOLDER_LIST                 166
#define IDB_BITMAP1                     168
#define IDB_CHECK_STATE                 168
#define IDB_SABOUT                      169
#define IDB_SSECURITY                   170
#define IDB_SACCOUNT                    171
#define IDB_SADVANCED                   172
#define IDB_SBANDWIDTH                  173
#define IDB_SGENERAL                    174
#define IDB_SPROXIES                    175
#define IDI_SECOND_SYNCING              176
#define IDC_GENERAL_BTN                 1000
#define IDC_LOCATION_EDT                1001
#define IDC_ACCOUNT_BTN                 1002
#define IDC_DRIVE_CBO                   1003
#define IDC_BANDWIDTH_BTN               1004
#define IDC_UNLINK_BTN                  1005
#define IDC_PROXIES_BTN                 1006
#define IDC_DOWNLIMIT_RDO               1007
#define IDC_CHILDREN_POS                1008
#define IDC_UPLOADLIMIT_RDO             1009
#define IDC_OK_BTN                      1010
#define IDC_DOWNRATE_RDO                1011
#define IDC_CANCEL_BTN                  1012
#define IDC_DOWNRATE_EDT                1013
#define IDC_APPLY_BTN                   1014
#define IDC_UPLOADRATE_EDT              1015
#define IDC_UPLOADAUTO_RDO              1016
#define IDC_MOVE_LOCATION_BTN           1018
#define IDC_MANUALPROXY_RDO             1019
#define IDC_SYSMSG_CHK                  1020
#define IDC_AUTH_CHK                    1020
#define IDC_AUTORUN_CHK                 1021
#define IDC_TYPE_CBO                    1022
#define IDC_AUTOUPDATE_CHK              1022
#define IDC_PASSWORD_CHK                1023
#define IDC_ABOUT_BTN                   1024
#define IDC_VALIDATE_BTN                1024
#define IDC_LOCAL_PWD_BTN               1024
#define IDC_CLIENT_PWD_BTN              1024
#define IDC_NOPROXY_RDO                 1025
#define IDC_SECURITY_BTN                1025
#define IDC_AUTOPROXY_RDO               1026
#define IDC_PROXY_UNAME_EDT             1027
#define IDC_BUTTON_POS                  1027
#define IDC_AUTH_RDO                    1028
#define IDC_NEWPWD_ADD_EDT              1028
#define IDC_UPLOADRATE_RDO              1029
#define IDC_VALPWD_ADD_EDT              1029
#define IDC_PROXY_PASSWD_EDT            1030
#define IDC_VALPWD_CHG_EDT              1030
#define IDC_PORT_EDT                    1031
#define IDC_CHANGE_USERPWD_SYSLINK      1031
#define IDC_SERV_EDT                    1032
#define IDC_OLDPWD_CHG_EDT              1032
#define IDC_NEWPWD_CHG_EDT              1033
#define IDC_OLDPWD_CHG_STC              1034
#define IDC_NEWPWD_CHG_STC              1035
#define IDC_VALPWD_CHG_STC              1036
#define IDC_NEWPWD_ADD_STC              1037
#define IDC_VALPWD_ADD_STC              1038
#define IDC_TYPE_STC                    1039
#define IDC_SERV_STC                    1040
#define IDC_PORT_STC                    1041
#define IDC_PASSWD_STC                  1043
#define IDC_UNAME_STC                   1044
#define IDC_PCNAME_STC                  1045
#define IDC_MOVE_DAT_STC                1047
#define IDC_MOVE_STATUS_STC             1047
#define IDC_ADVANCED_BTN                1048
#define IDC_DIRE_SELECTION_BTN          1049
#define IDC_SELECTIVE_TREE              1050
#define IDC_FORCECTRL_BTN               1050
#define IDC_ADVANCE_MODE_BTN            1051
#define IDC_REMOUNT_BTN                 1051
#define IDC_PASSWORD_EDT                1052
#define IDC_VERSION_STC                 1052
#define IDC_SELECTIVE_STC               1053
#define IDC_APP_UPDATE_SYSLINK          1054
#define IDC_FORCECTRL_STC               1054
#define ID_AGENG_HELP                   32772
#define ID_OPEN_ROOTDIR                 32773
#define ID_APP_SUSPEND                  32774
#define ID_OPTIONS_OPEN                 32775
#define ID_PROCESS_STATUS               32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
